FROM node:24-alpine AS builder
WORKDIR /JobPortal/Backend
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:24-alpine
WORKDIR /JobPortal/Backend
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /JobPortal/Backend/dist ./dist
CMD ["node", "dist/server.js"]