# Stage 1: Build
FROM node:24-alpine AS builder
WORKDIR /JobPortal/Frontend

COPY package*.json ./
RUN npm ci

COPY . .

# Accept build args from docker-compose
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

# Stage 2: Nginx
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /JobPortal/Frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]